#! /bin/sh

DURATION=${1:-0.01}

# We use IO pin 27 - it is called gpio 2 in the wiring stuff.
# http://wiringpi.com/pins/
PORT=2

#### tell snake skin to push warning app to stack
curl http://snakeskin.s/api/push/irc

gpio mode $PORT out
gpio write $PORT 1
sleep $DURATION
gpio write $PORT 0
